USE [master]
GO
/****** Object:  Database [DB_DienThoai]    Script Date: 6/8/2023 1:58:34 PM ******/
CREATE DATABASE [DB_DienThoai]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_DienThoai', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQL2017\MSSQL\DATA\DB_DienThoai.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_DienThoai_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQL2017\MSSQL\DATA\DB_DienThoai_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DB_DienThoai] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_DienThoai].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_DienThoai] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_DienThoai] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_DienThoai] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_DienThoai] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_DienThoai] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_DienThoai] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DB_DienThoai] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_DienThoai] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_DienThoai] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_DienThoai] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_DienThoai] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_DienThoai] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_DienThoai] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_DienThoai] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_DienThoai] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DB_DienThoai] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_DienThoai] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_DienThoai] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_DienThoai] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_DienThoai] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_DienThoai] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DB_DienThoai] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_DienThoai] SET RECOVERY FULL 
GO
ALTER DATABASE [DB_DienThoai] SET  MULTI_USER 
GO
ALTER DATABASE [DB_DienThoai] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_DienThoai] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_DienThoai] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_DienThoai] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_DienThoai] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DB_DienThoai', N'ON'
GO
ALTER DATABASE [DB_DienThoai] SET QUERY_STORE = OFF
GO
USE [DB_DienThoai]
GO
/****** Object:  Table [dbo].[Account]    Script Date: 6/8/2023 1:58:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account](
	[AccId] [int] NOT NULL,
	[AccName] [varchar](100) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[FullName] [nvarchar](70) NOT NULL,
	[Gender] [bit] NOT NULL,
	[Birthday] [datetime] NOT NULL,
	[Address] [nvarchar](200) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK__Account__91CBC37876CC4E71] PRIMARY KEY CLUSTERED 
(
	[AccId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Acount_Roles]    Script Date: 6/8/2023 1:58:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Acount_Roles](
	[Id] [int] NOT NULL,
	[Userid] [int] NOT NULL,
	[Roleid] [int] NOT NULL,
 CONSTRAINT [PK__Acount_R__3214EC0794F36EC5] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 6/8/2023 1:58:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[CategoryId] [nvarchar](100) NOT NULL,
	[CategoryName] [nvarchar](200) NOT NULL,
	[Description] [nvarchar](200) NOT NULL,
	[Status] [bit] NOT NULL,
	[CreateDate] [date] NOT NULL,
 CONSTRAINT [PK__Category__19093A0BF26213BA] PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderDetail]    Script Date: 6/8/2023 1:58:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetail](
	[OrderDetailId] [int] NOT NULL,
	[OrderId] [int] NOT NULL,
	[ProdId] [int] NOT NULL,
	[Price] [float] NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK__OrderDet__D3B9D36C6BCE4B43] PRIMARY KEY CLUSTERED 
(
	[OrderDetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderProduct]    Script Date: 6/8/2023 1:58:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderProduct](
	[OrderId] [int] NOT NULL,
	[AccId] [int] NOT NULL,
	[OrderDate] [date] NOT NULL,
	[TotalPrice] [float] NOT NULL,
	[Address] [nvarchar](200) NOT NULL,
	[PhoneNumber] [varchar](20) NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK__OrderPro__C3905BCF078F97BF] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 6/8/2023 1:58:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[ProdId] [int] NOT NULL,
	[ProdName] [nvarchar](200) NOT NULL,
	[CategoryId] [nvarchar](100) NOT NULL,
	[ShortDescription] [nvarchar](300) NOT NULL,
	[Description] [ntext] NOT NULL,
	[Price] [float] NOT NULL,
	[SaleOfff] [float] NOT NULL,
	[ImageUrl] [nvarchar](200) NOT NULL,
	[Tag] [nvarchar](100) NOT NULL,
	[Quanity] [int] NOT NULL,
	[Stautus] [bit] NOT NULL,
 CONSTRAINT [PK__Product__042785E5527BB3A9] PRIMARY KEY CLUSTERED 
(
	[ProdId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 6/8/2023 1:58:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[Id] [int] NOT NULL,
	[name] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Acount_Roles]  WITH CHECK ADD FOREIGN KEY([Roleid])
REFERENCES [dbo].[Roles] ([Id])
GO
ALTER TABLE [dbo].[Acount_Roles]  WITH CHECK ADD  CONSTRAINT [FK_Acount_Roles_Account] FOREIGN KEY([Userid])
REFERENCES [dbo].[Account] ([AccId])
GO
ALTER TABLE [dbo].[Acount_Roles] CHECK CONSTRAINT [FK_Acount_Roles_Account]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetail_OrderProduct] FOREIGN KEY([OrderId])
REFERENCES [dbo].[OrderProduct] ([OrderId])
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_OrderDetail_OrderProduct]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetail_Product] FOREIGN KEY([ProdId])
REFERENCES [dbo].[Product] ([ProdId])
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_OrderDetail_Product]
GO
ALTER TABLE [dbo].[OrderProduct]  WITH CHECK ADD  CONSTRAINT [FK__OrderProd__Statu__4316F928] FOREIGN KEY([AccId])
REFERENCES [dbo].[Account] ([AccId])
GO
ALTER TABLE [dbo].[OrderProduct] CHECK CONSTRAINT [FK__OrderProd__Statu__4316F928]
GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK__Product__Stautus__403A8C7D] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Category] ([CategoryId])
GO
ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK__Product__Stautus__403A8C7D]
GO
USE [master]
GO
ALTER DATABASE [DB_DienThoai] SET  READ_WRITE 
GO
